### ISSUE TITLE
ÖZKAN TUNCEL- Mobile(Kotlin, Java ve Flutter)- Zorunlu Staj

### ISSUE THREAD

**Issue by ozkantuncel** [VB10/2023-staj#131]
Tanıtım:
Ben Özkan Tuncel.  Java, Kotlin, Flutter ve Python gibi dillerde programlama yeteneğine sahibim. Fırat Üniversitesi Mobil Uygulama Geliştirme takımında Kotlin ile mobil uygulama geliştirme projelerinde çalıştım. Ayrıca, 100sClub da gönülü olarak staj yapıyorum.
Üniversite: Fırat Üniversitesi- Yazılım Mühendisliği
Uzaktan: Kabul ediyorum ve zorunlu 20 gün 
Konum: Malatya 
Mail Adresi: ozkantuncel2016@gmail.com
Linkedin:  https://www.linkedin.com/in/ozkantuncel/
CV: [Özkan Tuncel](https://github.com/VB10/2023-staj/files/11530841/Ozkan.Tuncel.CV.pdf)

**Comment by VB10** [comment]
Merhaba arkadaşlar, sizler için elimden geldiğince herkese yazdım, LinkedIn postları paylaştım ve elimden gelen bir çok arkadaşa erişip staj bulmasına yardımcı oldum. Bu saate kadar size verebileceğim 'ben olsaydım' diyeceğim:

- Bu repoyu LinkedIn'de paylaşıp sadece kendim için değil, benim gibi arkadaşlar için staj arıyoruz demeniz.
- Unutmayın tek başınıza belki kimse görmez ama hepiniz aynı sesi çıkarabilirseniz, yine aranızdan bir arkadaş belki kazanır.

Ek olarak bir çoğunuzu inceledim, gördüm. Hepiniz bugüne kadar yaptıklarınız için ellerinize, emeklerinize sağlık. Staj bulamadın diyelim, okul uzadı vs. asla durma. Çalış, ayağa kalk. Düşmediğin sürece yenilmezsin. Kendimden biliyorum, tüm stajları red yemiş, naylon staj teklifi gelmiş vb.

Unutmayın: Umutsuz durumlar yoktur, umutsuz insanlar vardır. Ben hiç bir zaman umudumu yitirmedim!

Sevgilerimle, Repo önümüzdeki hafta gibi artık arşivlenecek. Bu staj dönemi bittiği için. Umarım tekrar böyle bir repo açmak zorunda kalmayız.

Güzellikler sizinle olsun. cc:  @ozkantuncel
