### ISSUE TITLE
Şerife Gül Korkut - Web / Data Analysis Zorunlu Staj

### ISSUE THREAD

**Issue by gulkorkut** [VB10/2023-staj#135]
Ben Şerife Gül KORKUT. Abdullah Gül Üniversitesi Bilgisayar Mühendisliği 3.sınıf öğrencisiyim. 30 iş günü zorunlu stajım bulunuyor. Daha önce Yapı Kredi ve ASPILSAN Enerji şirketlerinde web backend geliştirme üzerine staj yaptım. Web development ve data analysis alanlarında staj yapabilirim. Okulum uzaktan stajı da kabul etmektedir. 
Bulunduğum il: Ankara
Mail: serifegulkorkut@gmail.com
Linkedin: https://www.linkedin.com/in/serifegulkorkut/
CV: https://drive.google.com/drive/folders/1XsfjKB4nrBlyiS-0jjGHFs2F-64hITXX?usp=sharing

**Comment by bakiabaci** [comment]
Merhaba Gül,

Staj süreci resmi olarak mı ilerleyecek? Data alanına ilgi duyuyor musun? Bu konu hakkında görüşme sağlayabiliriz istersen.

İyi çalışmalar.

**Comment by VB10** [comment]
@gulkorkut

**Comment by gulkorkut** [comment]
> Merhaba Gül,
> 
> Staj süreci resmi olarak mı ilerleyecek? Data alanına ilgi duyuyor musun? Bu konu hakkında görüşme sağlayabiliriz istersen.
> 
> İyi çalışmalar.

Merhabalar, zorunlu stajım olduğu için resmi ilerleyecek. Evet data alanına ilgi duyuyorum. Görüşmek isterim.
