### ISSUE TITLE
Zorunlu Staj - Web Geliştirme

### ISSUE THREAD

**Issue by muhammedkalabasi10** [VB10/2023-staj#153]
Ben Muhammed Kalabaşı. Marmara Üniversitesi'nde bilgisayar mühendisliği 3.sınıf öğrencisiyim. Yaz için zorunlu stajım bulunuyor. Daha önce; React, Node.js, Python(FastAPI), Express.js kullandığım projeler ve OOP yaklaşımıyla Java Swing projeleri ve bunun dışında okul için projeler geliştirdim. Şu an bireysel olarak Spring Boot öğreniyorum. 
Linkedin: https://www.linkedin.com/in/muhammed-kalaba%C5%9F%C4%B1-116287248/
Github: https://github.com/muhammedkalabasi10
CV: 
[CV - Muhammed Kalabaşı_e.pdf](https://github.com/VB10/2023-staj/files/11533857/CV.-.Muhammed.Kalabasi_e.pdf)

**Comment by VB10** [comment]
Merhaba arkadaşlar, sizler için elimden geldiğince herkese yazdım, LinkedIn postları paylaştım ve elimden gelen bir çok arkadaşa erişip staj bulmasına yardımcı oldum. Bu saate kadar size verebileceğim 'ben olsaydım' diyeceğim:

- Bu repoyu LinkedIn'de paylaşıp sadece kendim için değil, benim gibi arkadaşlar için staj arıyoruz demeniz.
- Unutmayın tek başınıza belki kimse görmez ama hepiniz aynı sesi çıkarabilirseniz, yine aranızdan bir arkadaş belki kazanır.

Ek olarak bir çoğunuzu inceledim, gördüm. Hepiniz bugüne kadar yaptıklarınız için ellerinize, emeklerinize sağlık. Staj bulamadın diyelim, okul uzadı vs. asla durma. Çalış, ayağa kalk. Düşmediğin sürece yenilmezsin. Kendimden biliyorum, tüm stajları red yemiş, naylon staj teklifi gelmiş vb.

Unutmayın: Umutsuz durumlar yoktur, umutsuz insanlar vardır. Ben hiç bir zaman umudumu yitirmedim!

Sevgilerimle, Repo önümüzdeki hafta gibi artık arşivlenecek. Bu staj dönemi bittiği için. Umarım tekrar böyle bir repo açmak zorunda kalmayız.

Güzellikler sizinle olsun. cc:  @muhammedkalabasi10
