### ISSUE TITLE
Yiğit Ergün -Frontend Developer

### ISSUE THREAD

**Issue by yigitergun4** [VB10/2023-staj#197]
- Ben Yiğit Ergün Marmara Üniversitesi Almanca Yönetim Bilişim Sistemleri 2.Sınıf öğrencisiyim. 
[CV YİĞİT Ergün (1) (1).pdf](https://github.com/VB10/2023-staj/files/11559869/CV.YIGIT.Ergun.1.1.pdf)

**Comment by VB10** [comment]
Yiğit burada zorunlu staj ve en üstte paylaştığım formatta paylaşıyoruz buna uyarsak sevinirim @yigitergun4
