### ISSUE TITLE
Hüseyin Sefa Akçay - Mobile veya Backend (Flutter/Java/Python/C#) - Zorunlu 20 gün yaz stajı

### ISSUE THREAD

**Issue by hsefakcay** [VB10/2023-staj#208]
hsefakcay@gmail.com
[cv.pdf](https://github.com/VB10/2023-staj/files/11568225/cv.pdf)

**Comment by VB10** [comment]
Formata uygun benim gösterdiğim gibi açar mısın kapatıyorum tekrar güncellersin
