### ISSUE TITLE
Eren Coşkun Frontend - Backend- Mobile

### ISSUE THREAD

**Issue by erencsknn** [VB10/2023-staj#21]
-Ben Eren 23 yaşındayım Trakya Üniversitesi Bilgisayar Mühendisliği 4. sınıf öğrencisiyim. React.js ve ReactNative kütüphanelerini kullanarak web ve mobile uygulamalar geliştiriyorum. Şu anda aktif olarak 20 iş günü zorunlu yazılım stajım bulunmakta. 

Üniversite : Trakya Üniversitesi
Uzaktan Staj kabul ediyorum 
Bulunduğum İl : Bursa
Mail : erencoskunoffical@gmail.com
LinkedIn : https://www.linkedin.com/in/erencoskun14/
GitHub : https://github.com/erencsknn
CV : [EREN-COSKUN-CV-TR.pdf](https://github.com/VB10/2023-staj/files/11516173/EREN-COSKUN-CV-TR.pdf)

**Comment by VB10** [comment]
vbt stajı için gün içerisinde iletiyorum (11) **eğer bulduysan lütfen haber ver başka arkadaşı alalım**

**Comment by VB10** [comment]
ben iletmiyorum o zaman cunku staj tarihleri standar genelde ondan baska arkadasi alalim @erencsknn obur taraf olur muhmtelen

**Comment by erencsknn** [comment]
Veli Bey benim de staj tarihlerim esnek zaten temmuz ortasından eylül sonuna kadar yapabiliyorum. Fakat bu bulduğum şirket haziranın başında başlatıyor o yüzden bir takım sıkıntılar oldu. Bir saat kadar bekletebilir misiniz rica etsem size dönüş sağlasam. @VB10

**Comment by VB10** [comment]
tamam senı de ilettim sen o taraf ile yapar yapmazsan iletirsin

**Comment by erencsknn** [comment]
Çok teşekkür ederim
