### ISSUE TITLE
Şükran Gülbike Aydın-Zorunlu 24 günlük Staj(Java, Spring Boot)

### ISSUE THREAD

**Issue by gulbikee** [VB10/2023-staj#225]
Merhabalar Ben Şükran Gülbike Aydın . Erciyes Üniversitesi Bilgisayar Mühendisliği 4.sınıf öğrencisiyim. 24 günlük zorunlu stajım için staj yeri arayışındayım
Linkedin: [https://www.linkedin.com/in/g%C3%BClbike-ayd%C4%B1n-ab048b18b/](url)
Github: [https://github.com/gulbikee](url)
Cv: [Sukran Gulbike Aydin-CV (1).pdf](https://github.com/VB10/2023-staj/files/11582702/Sukran.Gulbike.Aydin-CV.1.pdf)

**Comment by VB10** [comment]
Merhaba arkadaşlar, sizler için elimden geldiğince herkese yazdım, LinkedIn postları paylaştım ve elimden gelen bir çok arkadaşa erişip staj bulmasına yardımcı oldum. Bu saate kadar size verebileceğim 'ben olsaydım' diyeceğim:

- Bu repoyu LinkedIn'de paylaşıp sadece kendim için değil, benim gibi arkadaşlar için staj arıyoruz demeniz.
- Unutmayın tek başınıza belki kimse görmez ama hepiniz aynı sesi çıkarabilirseniz, yine aranızdan bir arkadaş belki kazanır.

Ek olarak bir çoğunuzu inceledim, gördüm. Hepiniz bugüne kadar yaptıklarınız için ellerinize, emeklerinize sağlık. Staj bulamadın diyelim, okul uzadı vs. asla durma. Çalış, ayağa kalk. Düşmediğin sürece yenilmezsin. Kendimden biliyorum, tüm stajları red yemiş, naylon staj teklifi gelmiş vb.

Unutmayın: Umutsuz durumlar yoktur, umutsuz insanlar vardır. Ben hiç bir zaman umudumu yitirmedim!

Sevgilerimle, Repo önümüzdeki hafta gibi artık arşivlenecek. Bu staj dönemi bittiği için. Umarım tekrar böyle bir repo açmak zorunda kalmayız.

Güzellikler sizinle olsun. cc:  @gulbikee
