### ISSUE TITLE
İBRAHİM ÖZKARDEŞ - MOBILE/BACKEND/GAME

### ISSUE THREAD

**Issue by ibrahimozkardes** [VB10/2023-staj#3]
Merhaba ben İbrahim, Yazılım Mühendisliği 2. sınıf öğrencisiyim.
C# ile eğitim kapsamında ufak projeler, Web alanında yine denemeler ve küçük projeler geliştirdim. Şimdi ise mobil geliştirmeye yönelmek istiyorum. Bunun için kendim de adımlar atmaktayım, şu an o yönde ilerliyorum. Ayrıca oyun geliştirmeye ve bankalarda yapılan yazılıma da ilgi duyuyorum ve yazılanları merak etmekteyim.
Açıkçası ilk stajım ve sektörün içine hiç girmedim. İlk stajım bana biraz da yol gösterici olsun istiyorum.
Stajım en az 20 gün olmalı. 1 ay süreyle yapmayı tercih ederim. Fakat daha uzun süreli stajlara da açığım yaz tatili elverdiği sürece.
Teşekkür ederim.

• Karadeniz Teknik Üniversitesi
• Stajımı yüz yüze tercih ederim.
• Kocaeli
• ibrahimozkardes@outlook.com
• [LinkedIn](https://www.linkedin.com/in/ibrahim-%C3%B6zkarde%C5%9F-035b07203)

**Comment by VB10** [comment]
vbt stajı için gün içerisinde iletiyorum Muhammed (2) **eğer bulduysan lütfen haber ver başka arkadaşı alalım**

**Comment by ibrahimozkardes** [comment]
Hayır, hala arayış içindeyim. Henüz bulamadım. Teşekkür ederim, çok sevindimm :)

**Comment by ibrahimozkardes** [comment]
Teşekkür ederim, stajım ayarlandı. Kapatıyorum issueyi. :))
