### ISSUE TITLE
KERİM ŞENTÜRK - BACKEND (JAVA, SPRING BOOT, MYSQL) , NETWORK

### ISSUE THREAD

**Issue by kerimsenturk5734** [VB10/2023-staj#308]
1. Merhaba adım Kerim, 21 yaşındayım. 3. sınıftayım ve 40 günlük zorunlu yaz stajım var. Java Spring boot ile web üzerinde çalışıyorum. Backend' imi görselleştirecek kadar React.js biliyorum.  Ayrıca medium üzerinde öğrendiğim konuları hakkında yazılar yazıyorum. Derslerim için yaptığım projeleri ve diğer sosyal medya hesaplarımı profilimden inceleyebilirsiniz.
2. Kastamonu Üniversitesi Bilgisayar Mühendisliği 3. sınıf.
3. Uzaktan staj kabul ediliyor.
4. İstanbul
5. kerimsenturk2002@outlook.com
6. https://www.linkedin.com/in/kerim-%C5%9Fent%C3%BCrk-784a3220a/
7. CV [KERİM ŞENTÜRK.pdf](https://github.com/VB10/2023-staj/files/11630340/KERIM.SENTURK.pdf)

**Comment by VB10** [comment]
Merhaba arkadaşlar, sizler için elimden geldiğince herkese yazdım, LinkedIn postları paylaştım ve elimden gelen bir çok arkadaşa erişip staj bulmasına yardımcı oldum. Bu saate kadar size verebileceğim 'ben olsaydım' diyeceğim:

- Bu repoyu LinkedIn'de paylaşıp sadece kendim için değil, benim gibi arkadaşlar için staj arıyoruz demeniz.
- Unutmayın tek başınıza belki kimse görmez ama hepiniz aynı sesi çıkarabilirseniz, yine aranızdan bir arkadaş belki kazanır.

Ek olarak bir çoğunuzu inceledim, gördüm. Hepiniz bugüne kadar yaptıklarınız için ellerinize, emeklerinize sağlık. Staj bulamadın diyelim, okul uzadı vs. asla durma. Çalış, ayağa kalk. Düşmediğin sürece yenilmezsin. Kendimden biliyorum, tüm stajları red yemiş, naylon staj teklifi gelmiş vb.

Unutmayın: Umutsuz durumlar yoktur, umutsuz insanlar vardır. Ben hiç bir zaman umudumu yitirmedim!

Sevgilerimle, Repo önümüzdeki hafta gibi artık arşivlenecek. Bu staj dönemi bittiği için. Umarım tekrar böyle bir repo açmak zorunda kalmayız.

Güzellikler sizinle olsun. cc:  @kerimsenturk5734
