### ISSUE TITLE
Eren Mollaoğlu - Android(Kotlin)

### ISSUE THREAD

**Issue by ErenMlg** [VB10/2023-staj#4]
- Merhabalar ben Eren Mollaoğlu, 2.Sınıf 20 günlük zorunlu yaz stajım bulunmakta, stajımı kendimi geliştirdiğim alan olan android üzerine yapmak istemekteyim. Bir adet yayınlanmış uygulamam bulunmakta ve gün geçtikçe kendimi geliştirmekteyim.
- Kırklareli Üniversitesi
- Uzaktan staj olabilir
- İstanbul
- eren.mollaoglu@outlook.com
- [LINKEDIN ADRESİ](https://www.linkedin.com/in/mollaoglueren/)
- [Eren_Mollaoğlu_CV_EN.pdf](https://github.com/VB10/2023-staj/files/11514121/Eren_Mollaoglu_CV_EN.pdf)

**Comment by VB10** [comment]
vbt stajı için gün içerisinde iletiyorum (3) **eğer bulduysan lütfen haber ver başka arkadaşı alalım**

**Comment by ErenMlg** [comment]
Maalesef bulamadım

**Comment by ErenMlg** [comment]
VBT ile iletişime geçtim olumlu mail aldım başta Veli Hocam olmak üzere emeği geçen herkese çok teşekkürler.
