### ISSUE TITLE
Muhammed Burak Kesen Backend/Flutter Developer-Zorunlu/Yaz Stajı

### ISSUE THREAD

**Issue by MBurakKesen** [VB10/2023-staj#41]
### Hakkımda

- Mehmet Akif Ersoy Üniversitesi Bilgisayar Mühendisliği 3. Sınıf öğrencisiyim.
- Kendim yazılım geliştirme (Java, Python, C#) üzerine ve Flutter alanında ilgiliyim
### Deneyim

- Deneyimim bulunmamaktadır.
 ### Staj Arayışı

- Bursa içerisinde veya remote olarak staj arıyorum.
- Stajım zorunludur(Zorunlu staj belgesi mevcuttur) ve staj sigortası üniversite tarafından karşılanmaktadır.
- Çalışma süresi 30 iş günüdür. 
- Ücret beklentim yoktur.

### İletişim Bilgileri

- LinkedIn: https://www.linkedin.com/in/muhammed-burak-kesen-537805223
- E-Posta: kesenburak9@gmail.com
 ### CV

-[CV.pdf](https://github.com/VB10/2023-staj/files/11517354/CV.pdf)

**Comment by VB10** [comment]
vbt stajı için gün içerisinde iletiyorum (16) **eğer bulduysan lütfen haber ver başka arkadaşı alalım**

**Comment by MBurakKesen** [comment]
Başka bir arkadaşı alabilirsiniz, yardiminiz icin teşekkürler
