### ISSUE TITLE
Tolga Pirim - Mobile (Kotlin/Android) - Zorunlu Staj

### ISSUE THREAD

**Issue by tolgaprm** [VB10/2023-staj#45]
Merhaba! Ben Tolga Pirim👋
## Hakkımda
Android Developer olarak kendimi geliştirmeye, bu alanda yeni bilgiler öğrenmeye ve Tokat Gaziosmanpaşa Üniversitesi Bilgisayar Mühendisliği 3. sınıf öğrencisi olarak okumaya devam ediyorum. 
Kotlin, Java'da birçok projem bulunmaktadır. Şuan da KMM (Kotlin Multiplatform Mobile) öğrenmeye çalışıyorum.
Projelerimde Retrofit, Room, Hilt, Navigation, Coroutines-Flow, Firebase, Paging3, WorkManager gibi popüler kütüphaneleri kullandım. Bunlardan ayrı olarak Android tarafında yeni sayılabilecek Jetpack Compose kullanarak gerçekleştirdiğim projelerim mevcuttur.
GitHub hesabımdan projelerime göz atabilirsiniz.

## Staj Arayışı
Öğrenmiş olduğum bilgileri profesyonel bir ortamda kullanmak, yeni bilgiler öğrenmek ve tecrübe kazanmak için zorunlu staj arıyorum. (40 gün )
Kayseri'de ikamet ediyorum. İş gereği süreç boyunca ikamet edeceğim yeri değiştirebilirim - Uzaktan olması ilk tercihim.

## İletişim Bilgileri
*LinkedIn*: https://www.linkedin.com/in/tolga-pirim-7b0b10168
*E-posta:* tolgapirim25@gmail.com
*Cv:* 
[TolgaPirim_.pdf](https://github.com/VB10/2023-staj/files/11517710/TolgaPirim_.pdf)

**Comment by VB10** [comment]
40 gün staj uzun bir süre 20 20 olmasın o. Öyle ise haber ver ileticem seni @tolgaprm bende ki program 20 çünkü

**Comment by tolgaprm** [comment]
Merhaba abi, daha önce görüştüğüm yerden dün olumlu bir haber aldım. Bende issue'u kapatmayı unutmuşum. Yinede sana çok teşekkür ederim abi böyle bir girişimde bulunduğun için.

**Comment by VB10** [comment]
❤️ @tolgaprm
