### ISSUE TITLE
Mustafa Kemal Gordesli - .NET Backend Developer

### ISSUE THREAD

**Issue by mustafakemalgordesli** [VB10/2023-staj#53]
Balıkesir Üniversitesi Bilgisayar Mühendisliği 3. sınıf öğrencisiyim. Kendimi .NET ve Javascript teknolojilerinde geliştirmekteyim.
Yetiştirmek üzere bu alanda zorunlu staj arayışım bulunmaktadır. 

Linkedin: https://www.linkedin.com/in/mustafakemalgordesli/
Mail: m.kemalgordesli@gmail.com

**Comment by VB10** [comment]
vbt stajı için gün içerisinde iletiyorum (18) **eğer bulduysan lütfen haber ver başka arkadaşı alalım**

**Comment by mustafakemalgordesli** [comment]
Merhabalar,
Ben henüz staj bulamadım ama
geçen yaz dönemi vbt de staj yaptım hocam başka bir yerde staj yapmak benim
için daha faydalı olur.
Siz başka bir arkadaşa gönderin.
Saygılar

26 May 2023 Cum 09:24 tarihinde Veli Bacik ***@***.***> şunu
yazdı:

**Comment by VB10** [comment]
Yep teşekkür ederim bildirim için başka arkadaşa hemen yer verelim
