### ISSUE TITLE
Fatih YILMAZ -Flutter

### ISSUE THREAD

**Issue by Flattih** [VB10/2023-staj#56]
Selamlar Ben Fatih.Doğuş üniversitesi yazılım mühendisliği 3.sınıf öğrencisiyim,zorunlu stajım bulunmakta.Uzaktan staj kabul ediliyor.İzmir,İstanbul illerine ulaşım sağlayabilirim.Mail adresim fatihyilmazzz95@gmail.com.Linkedin hesabım https://www.linkedin.com/in/fatih-y%C4%B1lmaz-73b522200/.
Cv 
[Fatih+YILMAZ-Intern.pdf](https://github.com/VB10/2023-staj/files/11519308/Fatih%2BYILMAZ-Intern.pdf)

**Comment by VB10** [comment]
Merhaba arkadaşlar, sizler için elimden geldiğince herkese yazdım, LinkedIn postları paylaştım ve elimden gelen bir çok arkadaşa erişip staj bulmasına yardımcı oldum. Bu saate kadar size verebileceğim 'ben olsaydım' diyeceğim:

- Bu repoyu LinkedIn'de paylaşıp sadece kendim için değil, benim gibi arkadaşlar için staj arıyoruz demeniz.
- Unutmayın tek başınıza belki kimse görmez ama hepiniz aynı sesi çıkarabilirseniz, yine aranızdan bir arkadaş belki kazanır.

Ek olarak bir çoğunuzu inceledim, gördüm. Hepiniz bugüne kadar yaptıklarınız için ellerinize, emeklerinize sağlık. Staj bulamadın diyelim, okul uzadı vs. asla durma. Çalış, ayağa kalk. Düşmediğin sürece yenilmezsin. Kendimden biliyorum, tüm stajları red yemiş, naylon staj teklifi gelmiş vb.

Unutmayın: Umutsuz durumlar yoktur, umutsuz insanlar vardır. Ben hiç bir zaman umudumu yitirmedim!

Sevgilerimle, Repo önümüzdeki hafta gibi artık arşivlenecek. Bu staj dönemi bittiği için. Umarım tekrar böyle bir repo açmak zorunda kalmayız.

Güzellikler sizinle olsun. cc:  @Flattih
