### ISSUE TITLE
Osmancan Akagündüz - Flutter & IOS(Swift)

### ISSUE THREAD

**Issue by osmancan23** [VB10/2023-staj#57]
Fırat Üniversitesi 3.Sınıf yazılım mühendisliği öğrencisiyim. 2.5 yıldır farklı şirketlerde Flutter Developer olarak çalışma tecrübem bulunmakta. Yakın zamanda Swift kısmında da kendimi geliştirmeye başladım. Yazın 20 günlük zorunlu stajım bulunmakta. Kendi alanlarımda staj yapmak için güzel bir firma arıyorum.

Linkedin : https://www.linkedin.com/in/osmancan23/

Github : https://github.com/osmancan23

Email : osmancann23@gmail.com

**Comment by VB10** [comment]
vbt stajı için gün içerisinde iletiyorum (6) **eğer bulduysan lütfen haber ver başka arkadaşı alalım**

**Comment by osmancan23** [comment]
Abi merhaba . Staj acaba nasıl geçecek onunla ilgili bir bilgi var mı .
Geçen sene vbt yazılım da online eğitim şeklinde geçmişti. Flutter
konusunda 2.5 yıldır çalışıyorum zaten şirketlerde.Yakin zamanda iOS
alanina daldım. Bu stajımi iOS alanında projelerde ufaktan da olsa görev
alarak yapmak istiyorum. Bu konu hakkında bilgin var mı acaba ?

26 May 2023 Cum 09:26 tarihinde Veli Bacik ***@***.***> şunu
yazdı:

**Comment by VB10** [comment]
staj yine vbt uzerinde olacagi icin seni eliyorum baska bir arkadasi alalim senin yerine @osmancan23

**Comment by osmancan23** [comment]
tamamdır hocam

**Comment by osmancan23** [comment]
tamamdır hocam
