### ISSUE TITLE
Mücahit Şimşek - Mobile Flutter

### ISSUE THREAD

**Issue by mucahitsimsek** [VB10/2023-staj#6]
- Merhaba, ben Mücahit Şimşek. Bolu Abant İzzet Baysal Üniversitesi Bilgisayar Programcılığı 2. Sınıf öğrenciyim. Yaklaşık bir yıldır Flutter (BloC Pattern) ile ilgileniyorum öncesinde Java ile Android uygulamalar geliştirdim. 

- C#, SQL, C, Java orta seviye hakimim. 

- Bartın'da ikamet ediyorum. İş gereği süreç boyunca ikamet edeceğim yeri değiştirebilirim. 
- Staj günü için => Temmuz ile Ağustos aylarında, 30 iş günü olacaktır. 17 Temmuz 2023 - 25 Ağustos 2023 arasında olacaktır.

- mucahitsmsk74@gmail.com,
- [LinkedIn](https://www.linkedin.com/in/mucahit-simsek), 

- [CV](https://github.com/VB10/2023-staj/files/11515430/CV.-.Mucahit.Simsek.pdf)

**Comment by VB10** [comment]
vbt stajı için gün içerisinde iletiyorum (5) **eğer bulduysan lütfen haber ver başka arkadaşı alalım**

**Comment by mucahitsimsek** [comment]
Hocam teşekkürler. İlginiz sayesinde staj yerini buldum. Diğer arkadaşlara bol şans dilerim. İssue kapatıyorum.
