### ISSUE TITLE
Umut Baran Çiçek - (Phyton / Java - Cyber Security / Software Developer) 

### ISSUE THREAD

**Issue by umutbarancicek** [VB10/2023-staj#92]
Akdeniz Üniversitesi 4. Sınıf öğrencisiyim. 30 günlük zorunlu arayışı içerisindeyim. Uzaktan çalışmaya açığım. Onun dışında Antalya - Ankara 'da yüz yüze çalışma şartlarına da açığım.

[LinkedIn Profilim](https://www.linkedin.com/in/umut-baran-%C3%A7i%C3%A7ek-a37623230)

Mail : cicekumutbaran@gmail.com

Cv : [cv.pdf](https://github.com/VB10/2023-staj/files/11523120/cv.pdf)

**Comment by VB10** [comment]
Merhaba arkadaşlar, sizler için elimden geldiğince herkese yazdım, LinkedIn postları paylaştım ve elimden gelen bir çok arkadaşa erişip staj bulmasına yardımcı oldum. Bu saate kadar size verebileceğim 'ben olsaydım' diyeceğim:

- Bu repoyu LinkedIn'de paylaşıp sadece kendim için değil, benim gibi arkadaşlar için staj arıyoruz demeniz.
- Unutmayın tek başınıza belki kimse görmez ama hepiniz aynı sesi çıkarabilirseniz, yine aranızdan bir arkadaş belki kazanır.

Ek olarak bir çoğunuzu inceledim, gördüm. Hepiniz bugüne kadar yaptıklarınız için ellerinize, emeklerinize sağlık. Staj bulamadın diyelim, okul uzadı vs. asla durma. Çalış, ayağa kalk. Düşmediğin sürece yenilmezsin. Kendimden biliyorum, tüm stajları red yemiş, naylon staj teklifi gelmiş vb.

Unutmayın: Umutsuz durumlar yoktur, umutsuz insanlar vardır. Ben hiç bir zaman umudumu yitirmedim!

Sevgilerimle, Repo önümüzdeki hafta gibi artık arşivlenecek. Bu staj dönemi bittiği için. Umarım tekrar böyle bir repo açmak zorunda kalmayız.

Güzellikler sizinle olsun. cc:  @umutbarancicek
